AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-api-dynamo-lambda

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Parameters:
  TodoTableName:
    Type: String
    Default: Todos

Resources:
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TodoTableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  CreateTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: dist/functions/createTodo/app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        CreateTodo:
          Type: Api
          Properties:
            Path: /todos
            Method: post
      Environment:
        Variables:
          TODO_TABLE: !Ref TodoTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTableName
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/functions/createTodo/app.ts
  GetTodosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: dist/functions/getTodos/app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        CreateTodo:
          Type: Api
          Properties:
            Path: /todos
            Method: get
      Environment:
        Variables:
          TODO_TABLE: !Ref TodoTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTableName
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/functions/getTodos/app.ts
  DeleteTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: dist/functions/deleteTodo/app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        CreateTodo:
          Type: Api
          Properties:
            Path: /todos
            Method: delete
      Environment:
        Variables:
          TODO_TABLE: !Ref TodoTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTableName
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/functions/deleteTodo/app.ts
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"

Outputs:
  CreateTodoFunctionArn:
    Description: ARN of the CreateTodo Lambda function
    Value: !GetAtt CreateTodoFunction.Arn

  CreateTodoFunctionIamRole:
    Description: IAM Role ARN for CreateTodo Lambda function
    Value: !GetAtt CreateTodoFunctionRole.Arn
